### PR TITLE
fix(ui): filter "validatable" records for global action validate button

### LINKED ISSUE #740: [Global actions] Global action validation for Text2Text doesnt work if annotation is empty

### PR DESCRIPTION
**Pull request by leiyre**
fix #740

### CODE REVIEW

File: frontend/components/text2text/header/Text2TextHeader.vue [hunk 1]
```diff
@@ -58,7 +58,19 @@ export default {
       await this.validateAnnotations({
         dataset: this.dataset,
         agent: getUsername(this.$auth),
-        records: records,
+        records: records.map((record) => {
+          let modelPrediction = {};
+          modelPrediction.sentences = [{
+            text: record.prediction.sentences[0].text,
```
Comment (frascuchon) [inline frontend/components/text2text/header/Text2TextHeader.vue:65]: This line will fail if record has no predictions

**Review by frascuchon — CHANGES_REQUESTED** [review]

**Review by frascuchon — APPROVED** [review]
👍
