### PR TITLE
fix(#1447): change agent when validating records with annotation but default status

### LINKED ISSUE #1447: [Annotation agent] Agent is not changed when validating records with annotation but `default` status
**Describe the bug**
I have not reproduced this myself, so this should be tested. It was raised yesterday during a session with one of our production users.

The workflow:

- They created text classification records with both annotation and prediction and status = Default.
- In this way, it's easy for the annotators to just validate those records that are already labeled correctly.
- Users validate records (they actually review ~3000 per week). 
- The issue is that only records for which they change the annotation get assigned the annotation_agent. For those `validated` by accepting the annotations, the `annotation_agent` is still the `machine_process` agent.

I think the proper way would be to change the annotation_agent even if no annotation was modified as the user is confirming they agree with the annotation so the record is manually annotated.

**To Reproduce**
Not possible on my side today

### PR DESCRIPTION
**Pull request by leiyre**
fix #1447

This PR overwrites the agent when validating records with annotation but default status

### CODE REVIEW

File: frontend/components/text-classifier/results/RecordTextClassification.vue [hunk 1]
```diff
@@ -90,7 +90,9 @@ export default {
         this.dataset.labels.length === 2 && !this.dataset.isMultiLabel;
       return (
         this.record.status !== "Validated" &&
-        !isBinary &&
+        (!isBinary ||
+          (isBinary && this.record.annotation) ||
+          this.record.prediction) &&
```
Comment (frascuchon) [inline frontend/components/text-classifier/results/RecordTextClassification.vue]: Could we just remove these conditions? The cases where you can validate records using the `Validate` button should be:

1. has annotation  OR
2. has prediction OR
3. is a multi_label record

Those cases are covered by lines 96, 97 and 98

Comment (leiyre) [reply frontend/components/text-classifier/results/RecordTextClassification.vue]: absolutely right

**Review by frascuchon — APPROVED** [review]
YEAH!
