### PR TITLE
refactor(UI): set pagination as fixed footer

### LINKED ISSUE #402: [UI] Fix footer

### PR DESCRIPTION
**Pull request by leiyre**
fix #402

### CODE REVIEW

File: frontend/components/commons/results/ResultsList.vue [hunk 1]
```diff
@@ -138,11 +122,30 @@ export default {
...
+    padding-top: 180px;
+    padding-bottom: 5em;
     height: 100vh !important;
     overflow: auto;
     padding-left: 4em;
     padding-right: calc(4em + 45px);
+    .--annotation & {
+      padding-top: 240px;
+    }
+    .TokenClassification.--annotation & {
```
Comment (frascuchon) [inline frontend/components/commons/results/ResultsList.vue:135]:
```suggestion
     // TODO: Revise when new fixed header is ready
    .TokenClassification.--annotation & {
```

**Review by frascuchon — APPROVED** [review]
