### PR TITLE
fix(scroll): using new scroll component

### LINKED ISSUE #616: [Scrolling] Expected record view state IS lost after scroll
CPT2111111623-1024x598

For text2text, record view state is lost after scrolling the page. It's an expected behavior? Should we keep the same state when scrolling @Amelie-V @leiyre @dvsrepo @dcfidalgo ?

### PR DESCRIPTION
**Pull request by frascuchon**
Closes #616

### CODE REVIEW

File: frontend/components/commons/results/RecordExtraActions.vue [hunk 1]
```diff
@@ -16,15 +16,15 @@
...
     <a
       v-if="hasMetadata || allowChangeStatus"
       class="extra-actions__button"
       href="#"
-      @click.prevent="open = !open"
+      @click.prevent="idState.open = !idState.open"
       ><svgicon name="kebab-menu-h" width="20" height="20" color="#4A4A4A"
     /></a>
-    <div v-if="open" class="extra-actions__content">
+    <div v-if="idState.open" class="extra-actions__content">
```
Comment (frascuchon) [inline frontend/components/commons/results/RecordExtraActions.vue]: we should define component getters using internal idState properties.

File: frontend/components/commons/results/RecordExtraActions.vue [hunk 2]
```diff
@@ -102,7 +113,7 @@ export default {
       this.close();
     },
     close() {
-      this.open = false;
+      this.idState.open = false;
```
Comment (frascuchon) [inline frontend/components/commons/results/RecordExtraActions.vue]: We can also define computed props with setters, like doc [shows](https://vuejs.org/v2/guide/computed.html#Computed-Setter)

```javascript
// ...
computed: {
  open: {
    // getter
    get: function () {
      return this.idState.open
    },
    // setter
    set: function (newValue) {
       this.idState.open = newValue
    }
  }
}
// ...
```

File: frontend/components/text-classifier/results/ClassifierAnnotationArea.vue [hunk 3]
```diff
@@ -165,12 +175,12 @@ export default {
   watch: {
     appliedLabels(o, n) {
       if (o.some((l) => n.indexOf(l) === -1)) {
-        this.selectedLabels = this.appliedLabels;
+        this.idState.selectedLabels = this.appliedLabels;
```
Comment (frascuchon) [inline frontend/components/text-classifier/results/ClassifierAnnotationArea.vue]: ditto

**Review by frascuchon — COMMENTED** [review]
In general we should integrate the IdState provided by new virtual scroller as computed properties with setter part.

File: frontend/components/commons/results/ResultsList.vue [hunk 4]
```diff
@@ -77,9 +101,23 @@ export default {
...
+        return (
+          this.dataset.viewSettings.pagination.page *
+            this.dataset.viewSettings.pagination.size ===
+          this.dataset.viewSettings.pagination.maxRecordsLimit
+        );
+      }
+      return false;
+    },
+    metadata() {
+      if (this.visibleRecords.find(i => i.id === this.showMetadata)) {
```
Comment (frascuchon) [inline frontend/components/commons/results/ResultsList.vue]: Could we just keep the whole record item as `this.showMetadata` and fetch metadata from it instead find it in all visible records?

File: frontend/components/commons/results/ResultsList.vue [hunk 5]
```diff
@@ -77,9 +101,23 @@ export default {
...
+        return this.visibleRecords.find(i => i.id === this.showMetadata).metadata;
+      } else {
+        return false;
       }
-      return false
+    },
+    metadataTitle() {
+      return this.visibleRecords.find(i => i.id === this.showMetadata).recordTitle()
```
Comment (frascuchon) [inline frontend/components/commons/results/ResultsList.vue]: ditto

File: frontend/components/commons/results/ResultsList.vue [hunk 6]
```diff
@@ -96,26 +134,39 @@ export default {
...
     },
+    async onApplyMetadataFilter(metadata) {
+      this.onCloseMetadata();
+      this.search({
+        dataset: this.dataset,
+        query: { metadata: metadata },
+      });
+    },
+    onShowMetadata(id) {
+      this.showMetadata = id;
```
Comment (frascuchon) [inline frontend/components/commons/results/ResultsList.vue]: Better use the whole item instead just the id

File: frontend/components/text-classifier/results/ClassifierAnnotationArea.vue [hunk 7]
```diff
@@ -122,7 +156,7 @@ export default {
     },
     filteredLabels() {
       return this.sortedLabels.filter((label) =>
-        label.class.toLowerCase().match(this.searchText)
+        label.class.toLowerCase().match(this.idState ? this.searchText : undefined)
```
Comment (frascuchon) [inline frontend/components/text-classifier/results/ClassifierAnnotationArea.vue]: Why `this.idState` could be `undefined` ?

Comment (leiyre) [reply frontend/components/text-classifier/results/ClassifierAnnotationArea.vue]: I think the watcher interfered with idState

Comment (frascuchon) [reply frontend/components/text-classifier/results/ClassifierAnnotationArea.vue]: Then we can move `this.idState` validation inside `searchText` getter

```javascript
searchText: {
      get: function () {
        return this.idState ? this.idState.searchText : undefined;
      },
```
And, what about the rest of computed fields ? Should we need validate `idState` for all of them since it could be `undefined`?
