### PR TITLE
fix: Move "Show less" button to the end of entities list

### LINKED ISSUE #1779: Button enity-label gets covered by show less button
**Describe the bug**
With a lot labels the button gets covered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a TokenClassification dataset
2. Click on show more labels
3. See error

**Expected behavior**
I would expect to start a new-line.

**Screenshots**
image

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Rubrix Version [e.g. 0.10.0]: 1.x
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. rubrix:v0.10.0]: N.A.

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by leiyre**
closes #1779

This PR avoids the overlapping of the button and the entities, moving the button to the end of the list.

### CODE REVIEW

File: frontend/components/token-classifier/header/EntitiesHeader.vue [hunk 1]
```diff
@@ -67,14 +61,25 @@ export default {
           ...ent,
         }));
 
-      return this.showEntitySelector
+      return this.showExpandedList
         ? entities
-        : entities.slice(0, this.entitiesNumber);
+        : entities.slice(0, this.maxEntitiesNumber);
```
Comment (keithCuniah) [inline frontend/components/token-classifier/header/EntitiesHeader.vue]: code cleanning : create a method for the second part of the ternary operation

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]
