### PR TITLE
Fix Filters selector options filter

### LINKED ISSUE #33: Bug: Search in "Annotated as" not working properly
The search in the "Annotated as" filter does not work properly.

### PR DESCRIPTION
**Pull request by leiyre**
fix #33

### CODE REVIEW

File: frontend/components/commons/filters/SelectFilter.vue [hunk 1]
```diff
@@ -93,7 +93,7 @@ export default {
       }
       let filtered = Object.fromEntries(
         Object.entries(options).filter(([id, value]) =>
-          id.match(text.toLowerCase())
+          id.toLowerCase().match(text.toLowerCase())
```
Comment (frascuchon) [inline frontend/components/commons/filters/SelectFilter.vue:96]: @leiyre `text` is a selected option? In that case, could we just match the original values?

```javascript 
id.match(text)
```

Comment (leiyre) [reply frontend/components/commons/filters/SelectFilter.vue:96]: @frascuchon,`text` is any of available options, if we want case sensitive we can use `id.match(text)`. Is it ok case sensitive?
