### PR TITLE
fix: When going to a page superior than maximum available page, go to first

### LINKED ISSUE #2883: When going to a page superior than maximum available page, go to first page
Now if we go to a page number superior than the maximum page number, the ui stay on that page but does not have any data to show (since there is no record for that page). 
This can happens when : 
- we copy paste a url (for example https://dev.argilla.io/dataset/ff0046f3-5098-40e6-80e1-58945faa185c/annotation-mode?_page=**Change_to_a_big_number**&_status=pending).
- when we are at the last page from any status, do an action from clear/discard/submit and then refresh with F5 (since last merge in dev, we are showing an empty message instead)

### PR DESCRIPTION
**Pull request by leiyre**
# Description

If we go to a page number superior than the maximum page number, the ui will change to the first page to avoid to show empty page

Closes #2883

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

File: frontend/components/feedback-task/footer/Pagination.component.vue [hunk 1]
```diff
@@ -106,7 +106,10 @@ export default {
     },
   },
   mounted() {
-    this.currentPage = parseFloat(this.$route.query?._page) || 1;
+    this.currentPage =
+      this.currentPage > this.totalPages
+        ? parseFloat(this.$route.query?._page) || 1
+        : 1;
```
Comment (keithCuniah) [inline frontend/components/feedback-task/footer/Pagination.component.vue]: use computed to make line more simple

**Review by keithCuniah — APPROVED** [review]
