### PR TITLE
fix: Allow non-alphanumeric characters for login

### LINKED ISSUE #1879: Login does not work when password contains `&`
Running this:

```bash
 ARGILLA_LOCAL_AUTH_DEFAULT_PASSWORD='$2y$05$A1CKLGuguBmGykWG4J7d2uUdiQBHGRg8DaAF7r7qDCzLlmsnZmNN.' python -m argilla

```

where the default password is set to `12&45`, making login fail even for the correct password.

The login through the API docs still works.

### PR DESCRIPTION
**Pull request by leiyre**
# Description

This RP includes data encoding to allow non-alphanumeric characters for login.

Closes #1879

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

**How Has This Been Tested**

Please describe the tests that you ran to verify your changes. And ideally reference `tests`.

- [ ] Test A
- [ ] Test B

**Checklist**

- [ ] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I added comments to my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: frontend/pages/login.vue [hunk 1]
```diff
@@ -93,10 +93,13 @@ export default {
...
     },
     async userLogin() {
+      const { username, password } = this.login;
       try {
         await this.$store.dispatch("entities/deleteAll");
         await this.$auth.loginWith("authProvider", {
-          data: `username=${this.login.username}&password=${this.login.password}`,
+          data: `username=${encodeURIComponent(
+            username
+          )}&password=${encodeURIComponent(password)}`,
```
Comment (keithCuniah) [inline frontend/pages/login.vue]: code cleanning : it's better to not do too much things in one line => create string from factory function

**Review by keithCuniah — APPROVED** [review]

**Review by frascuchon — APPROVED** [review]
