### PR TITLE
fix(#821): Token classifier QA 2

### LINKED ISSUE #821: [NER] Add switch Prediction/annotation
Just like in Text2text show Prediction/annotation in 2 views

-  Prediction by default in explore
-  Annotation by default in annotate

### PR DESCRIPTION
**Pull request by leiyre**
fix #821

this PR includes some styling adjustments to the colors, the width of the tooltips, predicted labels visualization in stats... it also includes changes to the register margin and the position of the register checkbox.

### CODE REVIEW

File: frontend/components/token-classifier/results/TextSpans.vue [hunk 1]
```diff
@@ -114,6 +119,12 @@ export default {
     },
   },
   methods: {
+    reset(e) {
+      if (e.target === this.$refs.list) {
+        console.log("yesss");
```
Comment (frascuchon) [inline frontend/components/token-classifier/results/TextSpans.vue]:
```suggestion
```

**Review by frascuchon — APPROVED** [review]
