### PR TITLE
fix: Improve explanation readability

### LINKED ISSUE #1774: Difficult to read explanations in UI
When using shap to understand in which parts of the text the model its putting attention on, the following happens:

image

 As the probabilities of some transformers are heavily located on the extremes (or really close to 0 or to 1), the colours on the shap representation are very dark and it's difficult to read the words inside to make an analysis. Just by changing the intensity of this colours would be enough.

### PR DESCRIPTION
**Pull request by leiyre**
This PR decreases the intensity of the colors for good readability of words with high values

closes #1774

### CODE REVIEW

File: frontend/components/text-classifier/results/RecordExplain.vue [hunk 1]
```diff
@@ -60,7 +60,7 @@ export default {
         let percent = Math.round(Math.abs(grad) * 100);
         if (percent !== 0) {
           /* eslint-disable no-mixed-operators */
-          const p = 1.5; // color sensitivity (values from 1 to 4)
+          const p = 1; // color sensitivity (values from 1 to 4)
```
Comment (keithCuniah) [inline frontend/components/text-classifier/results/RecordExplain.vue]: rename the variable 'p' by a more explicit name (colorSensitivity ?)

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]
