### PR TITLE
fix: include viewBox for svg images in fields

### LINKED ISSUE #4016: [BUG-UI/UX] `questions-form` get pushed out of screen with too large images
**Describe the bug**

**To Reproduce**
Upload very wide divs.
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" id="0cf691313c5e4d14863a75d83a07fd57-0" class="displacy" width="1450" height="487.0" direction="ltr" style="max-width: none; height: 487.0px; color: #000000; background: #ffffff; font-family: Arial; direction: ltr">
<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="50">Rats</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="50">NOUN</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="225">are</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="225">AUX</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="400">various</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="400">ADJ</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="575">medium-</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="575">ADJ</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="750">sized,</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="750">ADJ</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="925">long-</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="925">ADV</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="1100">tailed</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="1100">VERB</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="397.0">
    <tspan class="displacy-word" fill="currentColor" x="1275">rodents.</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="1275">NOUN</tspan>
</text>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-0" stroke-width="2px" d="M70,352.0 C70,264.5 210.0,264.5 210.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-0" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">nsubj</textPath>
    </text>
    <path class="displacy-arrowhead" d="M70,354.0 L62,342.0 78,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-1" stroke-width="2px" d="M420,352.0 C420,89.5 1270.0,89.5 1270.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-1" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">amod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M420,354.0 L412,342.0 428,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-2" stroke-width="2px" d="M595,352.0 C595,264.5 735.0,264.5 735.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-2" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">advmod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M595,354.0 L587,342.0 603,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-3" stroke-width="2px" d="M770,352.0 C770,177.0 1265.0,177.0 1265.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-3" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">amod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M770,354.0 L762,342.0 778,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-4" stroke-width="2px" d="M945,352.0 C945,264.5 1085.0,264.5 1085.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-4" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">advmod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M945,354.0 L937,342.0 953,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-5" stroke-width="2px" d="M1120,352.0 C1120,264.5 1260.0,264.5 1260.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-5" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">amod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M1120,354.0 L1112,342.0 1128,342.0" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-0cf691313c5e4d14863a75d83a07fd57-0-6" stroke-width="2px" d="M245,352.0 C245,2.0 1275.0,2.0 1275.0,352.0" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-0cf691313c5e4d14863a75d83a07fd57-0-6" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">attr</textPath>
    </text>
    <path class="displacy-arrowhead" d="M1275.0,354.0 L1283.0,342.0 1267.0,342.0" fill="currentColor"/>
</g>
</svg>
```

**Expected behaviour**
I would expect them to become scrollable.

**Screenshots**
https://github.com/argilla-io/argilla/assets/25269220/925dfe69-bc10-4470-a4b9-479b43c90d3b

**Environment (please complete the following information):**
 - OS [e.g. iOS]: max
 - Browser [e.g. chrome, safari]: firefox
 - Argilla Version [e.g. 1.0.0]: 1.17
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.17

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by leiyre**
# Description

This PR prevents the layout from breaking when using large svg images

Closes #4016

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: frontend/components/feedback-task/container/fields/text-field/TextField.component.vue [hunk 1]
```diff
@@ -48,6 +48,24 @@ export default {
   setup(props) {
     return useTextFieldViewModel(props);
   },
+  computed: {
+    renderedText() {
```
Comment (damianpumar) [inline frontend/components/feedback-task/container/fields/text-field/TextField.component.vue]: From my point of view, the TextField does not have the responsibility to manage this case.
I think the problem is in the Markdown, right? did you have time to reade https://marked.js.org/using_pro ??

**Comment by davidberenstein1957** [comment]
Also, I'm not sure if it only occurs with SVG images?
