### PR TITLE
fix: Paste plain text in editable content for Feedback Task

### LINKED ISSUE #2958: Copying text without the copy button in `FeedbackDataset` results in weird textfield formatting
**Describe the bug**
Copying text without the copy button in `FeedbackDataset` results in weird textfield formatting

**To Reproduce**
1. Copy text without coppy button
2. Paste it in a text field

**Expected behavior**
I would expect to just get the text.

**Screenshots**
image

**Environment (please complete the following information):**
N.A.

**Additional context**

### PR DESCRIPTION
**Pull request by leiyre**
# Description

This PR forces to paste plain text in the content editable area for Feedback Task to avoid breaking the area and causing strange behavior

Closes #2958

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] I have merged the original branch into my forked branch
- [ ] I added relevant documentation
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [ ] I made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added relevant notes to the CHANGELOG.md file (See https://keepachangelog.com/)

### CODE REVIEW

File: frontend/components/text2text/results/ContentEditableFeedbackTask.vue [hunk 1]
```diff
@@ -81,6 +85,13 @@ export default {
       this.focus = status;
       this.$emit("on-change-focus", status);
     },
+    pastePlainText(event) {
+      if (this.focus && event.target.isContentEditable) {
+        event.preventDefault();
+        const text = event.clipboardData?.getData("text/plain");
```
Comment (keithCuniah) [inline frontend/components/text2text/results/ContentEditableFeedbackTask.vue]: with the optional chaining `key?.key...` means that the const `text` could be equal to `undefined`, the user will be able to paste a value `undefined`.
To control the value in case the optional chainning is `undefined` you can combine the line with the nullish operator `??` and ensure that the value will be an empty string instead of `undefined`
```suggestion
        const text = event.clipboardData?.getData("text/plain") ?? "";
```
