### PR TITLE
fix: Remove "Help explain button" in Manage rule view

### LINKED ISSUE #1807: UI: Remove "Help explain button" in Manage rule view
**Describe the bug**
view screenshot

### PR DESCRIPTION
**Pull request by leiyre**
closes #1807

This PR removes the help explain button from the rules list view

### CODE REVIEW

File: frontend/components/text-classifier/header/TextClassificationHeader.vue [hunk 1]
```diff
@@ -59,6 +62,9 @@ export default {
     isMultiLabel() {
       return this.dataset.isMultiLabel;
     },
+    isRuleListView() {
+      return this.dataset.viewSettings.visibleRulesList;
+    },
```
Comment (keithCuniah) [inline frontend/components/text-classifier/header/TextClassificationHeader.vue:67]: Carefull with null => replace by this.dataset.viewSettings?.visibleRulesList || false

File: frontend/components/text-classifier/results/RecordExplain.vue [hunk 2]
```diff
@@ -62,7 +62,9 @@ export default {
           /* eslint-disable no-mixed-operators */
           const colorSensitivity = 1; // color sensitivity (values from 1 to 4)
           const logNumber = 100 / Math.log10(100) ** colorSensitivity;
-          percent = Math.round(Math.log10(percent) ** colorSensitivity * logNumber);
+          percent = Math.round(
+            Math.log10(percent) ** colorSensitivity * logNumber
+          );
```
Comment (keithCuniah) [inline frontend/components/text-classifier/results/RecordExplain.vue:70]: performance : you can breaks these operations in several computed in order to vue to only computed the one where the dependencies are changing

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]
