### PR TITLE
fix: Avoid closing the score filter when dragging the slider

### LINKED ISSUE #1876: UI: Score filter closes when you drag the slider
**Describe the bug**
Score filter closes when you drag the slider outside the select screen

**To Reproduce**
1. Go to dataset
2. Click on prediction / Score
3. Drag the slider outside of the dropdown
4. Filter closes

**Expected behavior**
Mantain opened the filter

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

### PR DESCRIPTION
**Pull request by leiyre**
This PR fixes the score filter selection, avoiding closing the score filter when dragging the slider outside of the filter content

see #1802
closes #1876

### CODE REVIEW

File: frontend/components/commons/header/filters/FiltersList.vue [hunk 1]
```diff
@@ -243,7 +249,7 @@ export default {
     },
   },
   methods: {
-    close() {
+    onClickOutside() {
       this.initialVisibleGroup = undefined;
```
Comment (keithCuniah) [inline frontend/components/commons/header/filters/FiltersList.vue]: in JS, if we want to assign to an empty value is better to assign to null instead of undefined. Can you check if the function is still working if this.initialVisibleGroup = null ?

**Review by keithCuniah — APPROVED** [review]

**Review by keithCuniah — APPROVED** [review]
