### PR TITLE
fix(#1008): set the event_timestamp when annotating TextClassifier

### LINKED ISSUE #1008: [Annotation] Annotating TextClassificationRecords sets the event_timestamp to None
When annotating text classification records via the web app, the event_timestap is lost.
```python
rec = rb.TextClassificationRecord(inputs="test", prediction=[("a", 0.5), ("b", 0.5)], event_timestamp=datetime.now())
rb.log(rec, "test_event_timestamp")
rb.load("test_event_timestamp")   # event_timestamp is fine
# annotate the record in the web app
rb.load("test_event_timestamp")   # event_timestamp is None
```

### PR DESCRIPTION
**Pull request by leiyre**
fix #1008

### CODE REVIEW

File: frontend/models/TextClassification.js [hunk 1]
```diff
@@ -26,11 +26,13 @@ class TextClassificationRecord extends BaseRecord {
     explanation,
     multi_label,
     predicted_as,
+    event_timestamp,
```
Comment (frascuchon) [inline frontend/models/TextClassification.js]: This will happen for all tasks. Could you include this change at main `BaseRecord` level?

**Review by frascuchon — CHANGES_REQUESTED** [review]

File: frontend/models/TextClassification.js (hunk 1 above)
Comment (leiyre) [reply frontend/models/TextClassification.js]: sure!

**Review by frascuchon — APPROVED** [review]
