### PR TITLE
Style: small fixes for Feedback Task

### LINKED ISSUE #2930: Update styles and content after QA
- [x]  Order of status in metrics: put the same than in the status selector
- [x]  Sidebar: Progress inside of Metrics
- [x]  Align the text “Read the guidelines…” on bottom with the title “submit..”
- [x]  Would be nice to add a hover effect on the outline of the rating component (slightly darker)
- [x]  Change button copy into toast: “Ok, continue.” for “Continue”
- [x]  Change “Description and annotations guideline” to "Annotation guidelines"
- [x]  Include 10px border radius for record and form

### PR DESCRIPTION
**Pull request by leiyre**
# Description

This PR includes some small changes for styles and content

- [x]  Order of status in metrics: put the same than in the status selector
- [x]  Sidebar: Progress inside of Metrics
- [x]  Align the text “Read the guidelines…” on bottom with the title “submit..”
- [x]  Would be nice to add a hover effect on the outline of the rating component (slightly darker)
- [x]  Change button copy into toast: “Ok, continue.” for “Continue”
- [x]  Change “Description and annotations guideline” to "Annotation guidelines"
- [x]  Include 10px border radius for record and form

Closes #2930

**Type of change**

- [x] Styles and little changes for static content

**Checklist**

- [x] I have merged the original branch into my forked branch
- [x] follows the style guidelines of this project
- [x] I did a self-review of my code
- [x] My changes generate no new warnings

### CODE REVIEW

File: frontend/components/feedback-task/feedbackTask.properties.js [hunk 1]
```diff
@@ -20,9 +20,14 @@ const CORRESPONDING_FIELD_COMPONENT_TYPE_FROM_API = Object.freeze({
...
+const FEEDBACK_TASK_PROPERTIES = Object.freeze({
+  CONTINUE: "Continue",
+});
+
 export {
   COMPONENT_TYPE,
   FIELD_COMPONENT_TYPE,
   CORRESPONDING_QUESTION_COMPONENT_TYPE_FROM_API,
   CORRESPONDING_FIELD_COMPONENT_TYPE_FROM_API,
+  FEEDBACK_TASK_PROPERTIES,
```
Comment (keithCuniah) [inline frontend/components/feedback-task/feedbackTask.properties.js]: renaming : LABEL_PROPERTIES

**Review by keithCuniah — APPROVED** [review]
