### PR TITLE
fix(UI): show annotation by default  in annotation view for Text2Text 

### LINKED ISSUE #545: [UI] Bug: Text2Text show annotation by default in annotation view
- [x] show annotation by default
- [x] center predictions navigation

### PR DESCRIPTION
**Pull request by leiyre**
fix #545

### CODE REVIEW

File: frontend/components/text2text/results/RecordText2Text.vue [hunk 1]
```diff
@@ -77,6 +77,13 @@ export default {
     this.initializeSentenceOrigin();
     this.initialRecord = Object.assign({}, this.record);
   },
+  watch: {
+    annotationEnabled(o, n) {
+      if (o !== n) {
```
Comment (frascuchon) [inline frontend/components/text2text/results/RecordText2Text.vue]:
```suggestion
    annotationEnabled(oldValue, newValue) {
      if (oldValue !== newValue) {
```

**Review by frascuchon — APPROVED** [review]
