### PR TITLE
fix: Remove extra type when highlighting the query in the text

### LINKED ISSUE #1758: Client: WeakList in Text Classification
**Describe the bug**
Sometimes, a chevron ">" is insert after the highlight query result

**To Reproduce**
1. Go to the a dataset with task as TextClassificaiton :  Dataset>sst2_with_explanations 
2. Select in the search query "a*"
3. Scroll down to result
4. See error as  sometimes you can see a highlight resul as "a' or ">a".

**Expected behavior**
The result should be without chevron 

**Screenshots**
image
or 
image

**Environment (please complete the following information):**
 - Windows:
 - Browser Chrome:
 - Rubrix Version Dev:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

**Additional context**
The problem is maybe in the component RecordExplain.vue at method explainFormatted()

### PR DESCRIPTION
**Pull request by leiyre**
closes #1758

This PR improves removes unused code and fixes multiple word replacement

### CODE REVIEW

File: frontend/plugins/highlight-search.js [hunk 1]
```diff
@@ -29,41 +29,21 @@ export default (context, inject) => {
...
-    });
-
-    return text;
+    const pattern = sortedKeywords.map(
+      (keyword) => `([^a-zA-ZÀ-ÿ\u00f1\u00d1]|^)${escapeRegExp(keyword)}`
+    );
+    const regExp = new RegExp(`${pattern.join("|")}`, "gmi");
+    return htmlText(text).replace(regExp, (matched) =>
+      htmlHighlightText(matched)
+    );
```
Comment (keithCuniah) [inline frontend/plugins/highlight-search.js]: Code cleanning : it's more recommend to do one task by function 
Here I can see that the highlightKeywords do : 
- a sort
- construct a pattern
- do something before return by replacing

=> it's better to break this in more little functions which will be reused here

File: frontend/plugins/highlight-search.js [hunk 2]
```diff
@@ -29,49 +29,37 @@ export default (context, inject) => {
...
+    return new RegExp(pattern, "gmi");
+  }
 
-  const highlightKeywords = function (text, keywords) {
-    const sortedKeywords = ([...keywords] || []).sort(
-      (a, b) => b.length - a.length
+  function replaceText(regex, text) {
+    return htmlText(text).replace(regex, (matched) =>
+      htmlHighlightText(matched)
     );
```
Comment (keithCuniah) [inline frontend/plugins/highlight-search.js:57]: Code cleanning : the deepest functions should appears after their implementation 

=> sortByLength/createPattern/replaceText should appears after their implementations in highlightKeywords function
